### ISSUE TITLE
Crash on :PeekOpen

### ISSUE THREAD

**Issue by elcih17** [toppair/peek.nvim#4]
OS
```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,4
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	64 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1
```

deno
```
$ deno --version
deno 1.26.1 (release, aarch64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
```

neovim
```
$ nvim --version
NVIM v0.9.0-dev-83-g34c7007c3
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
```

setup with Packer
```
    use {
      "toppair/peek.nvim",
      run = "deno task --quiet build:fast",
      config = function()
        vim.api.nvim_create_user_command("PeekOpen", require("peek").open, {})
        vim.api.nvim_create_user_command("PeekClose", require("peek").close, {})
      end,
    }
```

execute `:PeekOpen` then crash with these error messages (partial)
```
Peek error: 2022-10-17 11:55:51.859 deno[52621:4604222] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', re
ason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
^I0   CoreFoundation                      0x00000001bd8dd148 __exceptionPreprocess + 240
^I1   libobjc.A.dylib                     0x00000001bd627e04 objc_exception_throw + 60
^I2   CoreFoundation                      0x00000001bd9080cc _CFBundleGetValueForInfoKey + 0
^I3   AppKit                              0x00000001c03eb930 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisab
led] + 372
^I4   AppKit                              0x00000001c03d692c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 948
^I5   AppKit                              0x00000001c03d656c -[NSWindow initWithContentRect:styleMask:backing:defer:] + 56
^I6   5a78a907fb3b54a23d6ec12156baa6a1009 0x000000010a648fd0 _ZN7webview6detail22cocoa_wkwebview_engineC2EbPv + 672
^I7   5a78a907fb3b54a23d6ec12156baa6a1009 0x000000010a648d0c _ZN7webview7webviewC2EbPv + 72
^I8   5a78a907fb3b54a23d6ec12156baa6a1009 0x000000010a647afc _ZN7webview7webviewC1EbPv + 56
^I9   5a78a907fb3b54a23d6ec12156baa6a1009 0x000000010a647a50 webview_create + 56
^I10  deno                                0x00000001054d804c ffi_call_SYSV + 76
^I11  deno                                0x00000001054d7778 ffi_call_int + 1176
^I12  deno                                0x0000000104bb1b98 _ZN8deno_ffi12make_sync_fn28_$u7b$$u7b$closure$u7d$$u7d$17h66d69179d40fd057E +
1644
^I13  deno                                0x0000000104bab9b0 _ZN105_$LT$extern$u20$$u22$C$u22$$u20$fn$LP$A0$RP$$u20$.$GT$$u20$R$u20$as$u20$v
8..support..CFnFrom$LT$F$GT$$GT$7mapping4c_fn17h081844fa7f6729ccE + 64
^I14  deno                                0x0000000105672308 _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_
6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi + 684
^I15  deno                                0x00000001056719fc _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE + 224
^I16  deno                                0x00000001062de26c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 108
^I17  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I18  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I19  deno                                0x0000000106259dfc construct_stub_create_deopt_addr + 312
^I20  deno                                0x0000000106387220 Builtins_ConstructHandler + 704
^I21  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I22  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I23  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I24  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I25  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I26  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
^I27  deno                                0x000000010625c844 Builtins_InterpreterEntryTrampoline + 292
```

**Comment by ariel-frischer** [comment]
Same with:
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

MAC OS Monterey

**Comment by toppair** [comment]
@elcih17 @ariel-frischer

Can you try this branch?

`use({ 'toppair/peek.nvim', run = 'deno task --quiet build:fast', branch = 'separate-process' })`

**Comment by ariel-frischer** [comment]
@toppair the recommendation worked! Nice job :)

**Comment by elcih17** [comment]
@toppair It worked! Thanks!

**Comment by andrewferrier** [comment]
I have/had the same problem, and I tried the workaround with the branch, but it emitted a different error:

```
Peek error: error: Uncaught (in worker "webview") (in promise) TypeError: Deno.dlopen is not a function
    return Deno.dlopen(file, symbols);
                ^
    at prepare (file:///Users/username/.local/share/nvim/site/pack/packer/start/peek.nvim/public/webview.js:2897:17)
    at async file:///Users/username/.local/share/nvim/site/pack/packer/start/peek.nvim/public/webview.js:4025:13
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:153:21)
```

**Comment by toppair** [comment]
@andrewferrier

Doesn't look like you're using correct branch

`Uncaught (in worker "webview")`

There shouldn't be a worker anymore. There may be some problem with the build, make sure to completely remove `peek` and install it again from that branch.

Do you use `packer` or some other plugin/method to manage packages? My guess is that maybe you just checked out the branch in plugin directory. If that's the case you also need to run `deno task build:fast` in that directory.

Are you on mac too?

**Comment by CodePurble** [comment]
> I have/had the same problem, and I tried the workaround with the branch, but it emitted a different error:
> 
> ```
> Peek error: error: Uncaught (in worker "webview") (in promise) TypeError: Deno.dlopen is not a function
>     return Deno.dlopen(file, symbols);
>                 ^
>     at prepare (file:///Users/username/.local/share/nvim/site/pack/packer/start/peek.nvim/public/webview.js:2897:17)
>     at async file:///Users/username/.local/share/nvim/site/pack/packer/start/peek.nvim/public/webview.js:4025:13
> error: Uncaught (in promise) Error: Unhandled error in child worker.
>     at Worker.#pollControl (deno:runtime/js/11_workers.js:153:21)
> ```

I can confirm that this error is coming for me as well. I have tried fresh installs using both the default branch and the `separate-process` branch. I used `packer` for installing.

My config is the default provided by you, barring a workaround for #5

**Comment by toppair** [comment]
@CodePurble

Can you provide the output of `deno task build` (no `fast`) in plugin's directory?

**Comment by CodePurble** [comment]
Sure @toppair 

```
Warning deno task is unstable and may drastically change in the future
Task build deno run --allow-run --allow-net --allow-read=. --allow-write=. --allow-env --no-check scripts/build.js
Bundle file:///home/ramprakash/.local/share/nvim/site/pack/packer/start/peek.nvim/client/src/script.ts
Bundle file:///home/ramprakash/.local/share/nvim/site/pack/packer/start/peek.nvim/app/src/webview.ts
Emit "public/script.bundle.js" (13.36KB)
Bundle file:///home/ramprakash/.local/share/nvim/site/pack/packer/start/peek.nvim/app/src/main.ts
Emit "public/webview.js" (284.72KB)
Emit "public/main.bundle.js" (1.94MB)
```

and also, just FYI:

```sh
deno --version
deno 1.26.2 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.16
typescript 4.8.3
```

**Comment by toppair** [comment]
@CodePurble You're on linux and I believe the original error from this issue is mac specific, so it's not related.
