### ISSUE TITLE
peek crash

### ISSUE THREAD

**Issue by KimJungWha** [toppair/peek.nvim#42]
**Describe the bug**
When I use PeekOpen, peek.nvim opens a chromium window showing a markdown preview, waits for a few minutes, and crashes with an error output even though it does nothing

```
Peek error: error: Uncaught (in promise) TypeError: op_ws_send_ping is not a registered op
    at opAsync (ext:core/01_core.js:265:15)
    at ext:deno_websocket/01_websocket.js:533:17
    at Object.action (ext:deno_web/02_timers.js:147:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)
    at eventLoopTick (ext:core/01_core.js:172:21)
```

**To Reproduce**

```
:PeekOpen
```

**Expected behavior**
repaired successfully

**Screenshots**
![image](https://github.com/toppair/peek.nvim/assets/61445867/2c3dccc7-e4bd-492a-b9d7-8be7925e4ffc)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - `nvim --version`:
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
 - `deno --version`:
```
deno 1.33.0 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.1
typescript 5.0.3
```
 - plugin setup:

```lua
local present, peek = pcall(require, 'peek')

if not present then
    return
end


config = {
    auto_load = true,
    close_on_bdelete = true,
    update_on_change = true,
    filetype = {
        'md', 'markdown', 
        'telekasten', 
    },
    throttle_at = 2000000,
    throttle_time = 'auto',

    syntax = true,
    theme = 'light',

    app = 'chromium',
}


peek.setup(config)

vim.api.nvim_create_user_command('PeekOpen', require('peek').open, {})
vim.api.nvim_create_user_command('PeekClose', require('peek').close, {})
```
**Additional context**
None

**Comment by KimJungWha** [comment]
After update testing, the new version has been fixed
