### ISSUE TITLE
Could not open library: libwebkit2gtk-4.0.so.37

### ISSUE THREAD

**Issue by pandasoli** [toppair/peek.nvim#51]
**Describe the bug**
Right when I execute `:PeekOpen` the following error message is showed:
```
Peek error: error: Uncaught (in promise) Error: Could not open library: Could not open library: libwebkit2gtk-4.0.so.37: cannot open shared object fi
le: No such file or directory
    return Deno.dlopen(file, symbols);
                ^
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:458:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:595:10)
    at prepare (file:///home/panda/.local/share/nvim/lazy/peek.nvim/public/webview.js:2893:17)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///home/panda/.local/share/nvim/lazy/peek.nvim/public/webview.js:4021:13
```

**To Reproduce**
I just installed through Lazy.nvim, opened a Markdown file and ran `:PeekOpen`.

**Expected behavior**
Open a tab on my currently opened browser.

**Screenshots**
![image](https://github.com/toppair/peek.nvim/assets/76575902/ea709de6-a590-4d20-b258-61d235e516e7)

**Desktop (please complete the following information):**
 - OS: Gentoo GNU/Linux 6.6.5-gentoo-dist
 - `nvim --version`:
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4_build/include -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
 - `deno --version`:
```
deno 1.37.2 (release, x86_64-unknown-linux-gnu)
v8 11.8.172.13
typescript 5.2.2
```
 - plugin setup:
```lua
require 'lazy'.setup {
  {
    'toppair/peek.nvim',
    event = { 'VeryLazy' },
    build = 'deno task --quiet build:fast',
    config = function()
      require 'peek'.setup()
      -- refer to `configuration to change defaults`
      vim.api.nvim_create_user_command('PeekOpen', require('peek').open, {})
      vim.api.nvim_create_user_command('PeekClose', require('peek').close, {})
    end
  }
}
```
**Additional context**
As I use Gentoo I didn't install anything else but the deps that are provided.

**Comment by sazk07** [comment]
@pandasoli you could try `deno upgrade` to upgrade your deno instance. I only say this because I looked at the source code of the same file in my deno v1.41.2 and that line of code is not present there. It may have been refactored. In fact, that same file doesn't even have 4021 lines of code.

**Comment by toppair** [comment]
I would suggest installing library the error says is missing.

> Expected behavior
Open a tab on my currently opened browser.

With config you provided the `app` option defaults to `'webview'`. If you want it to open in browser you have to set it to `'browser'`, like so:

```lua
require('peek').setup({ app = 'browser' })
```
