### ISSUE TITLE
Cannot run `lua require'peek'.open()`

### ISSUE THREAD

**Issue by LC0117** [toppair/peek.nvim#7]
**Describe the bug**
Cannot run lua require'peek'.open()

**To Reproduce**
1. config
```lua
use({
 "toopair/peek.nvim",
 ft = 'markdown',
  run = 'deno task --quiet build:fast',
  config = function()
    require('peek').setup({
      theme = 'dark'
    })
  end
})
```

**Expected behavior**
Browser open with markdown preview.

**Screenshots**
logs
```
2022-10-20T14:42:03  ERROR Peek error: error: Uncaught (in promise) PermissionDenied: Requires net access to "github.com", run again with the --allow-net fla
g                                                                                                                                                             
    const download = await fetch(url);                                                                                                                        
                           ^                                                                                                                                  
    at opFetch (deno:ext/fetch/26_fetch.js:72:16)                                                                                                             
    at mainFetch (deno:ext/fetch/26_fetch.js:181:61)                                                                                                          
    at deno:ext/fetch/26_fetch.js:425:11                                                                                                                      
    at new Promise (<anonymous>)                                                                                                                              
    at fetch (deno:ext/fetch/26_fetch.js:388:20)                                                                                                              
    at protocolHttp (file:///Users/***/.local/share/nvim/site/pack/packer/opt/peek.nvim/public/webview.js:2687:28)                                         
    at fetchFile (file:///Users/***/.local/share/nvim/site/pack/packer/opt/peek.nvim/public/webview.js:2708:26)                                            
    at FileWrapper.fetch (file:///Users/***/.local/share/nvim/site/pack/packer/opt/peek.nvim/public/webview.js:2745:28)                                    
    at FileWrapper.get (file:///Users/***/.local/share/nvim/site/pack/packer/opt/peek.nvim/public/webview.js:2761:27)                                      
    at async cache (file:///Users/***/.local/share/nvim/site/pack/packer/opt/peek.nvim/public/webview.js:2769:12)                                          
```

**Desktop (please complete the following information):**
 - OS: macOS 12.6 arm64
 - `nvim --version`:
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```
 - `deno --version`:
```
deno 1.26.2 (release, aarch64-apple-darwin)
v8 10.7.193.16
typescript 4.8.3
```
 - plugin setup:
```lua
use({
 "toopair/peek.nvim",
 ft = 'markdown',
  run = 'deno task --quiet build:fast',
  config = function()
    require('peek').setup({
      theme = 'dark'
    })
  end
})
```
**Additional context**
I also tried `deno task run` in the project root. And got the weird message:
```
Task run deno run --allow-read --allow-write --allow-net --allow-env --allow-run --no-check public/main.bundle.js
Download https:/github.com/webview/webview_deno/releases/download/0.7.3/libwebview.aarch64.dylib
error: Uncaught (in promise) PermissionDenied: Requires net access to "github.com", run again with the --allow-net flag
    const download = await fetch(url);
```
The task specifies `allow-net`, but seems not work.

**Comment by toppair** [comment]
Can you reinstall and try again? Without `ft = 'markdown'` first.

**Comment by LC0117** [comment]
Thanks for the swift reply! Now the errors are gone, but I get an empty window as below when I disconnect network. Does this plugin need network to perform the preview?

<img width="1438" alt="截屏2022-10-20 18 23 01" src="https://user-images.githubusercontent.com/77481149/196923843-a8b1d056-5f4b-475f-a596-0590f3e0dcb5.png">

There is a `peek.log`:
```
INFO      23529    20/10/2022, 18:16:09.872  DENO_ENV: undefined 
INFO      23529    20/10/2022, 18:16:19.142  SIGNAL:  SIGINT
INFO      23582    20/10/2022, 18:16:23.079  DENO_ENV: undefined 
INFO      23582    20/10/2022, 18:16:43.973  webview closed, code: 0 
INFO      24145    20/10/2022, 18:20:01.131  DENO_ENV: undefined 
INFO      24145    20/10/2022, 18:20:05.967  webview closed, code: 0 
```

**Comment by LC0117** [comment]
> If 'disconnecting network' means that you can't run local server and/or use websockets then yes.

I meant without connecting to WLAN or LAN.

**Comment by toppair** [comment]
Your machine needs to be able to run a local server. You don't need to be connected to any kind of network to use this plugin.

**Comment by toppair** [comment]
Determine whether a server is running while `peek` window is open. If it is and it doesn't load preview, open new issue.
